# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setGeometry(QtCore.QRect(10, 10, 781, 101))
        self.frame_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.header1 = QtWidgets.QLabel(self.frame_header)
        self.header1.setGeometry(QtCore.QRect(0, 20, 781, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.header1.setFont(font)
        self.header1.setAlignment(QtCore.Qt.AlignCenter)
        self.header1.setObjectName("header1")
        self.header2 = QtWidgets.QLabel(self.frame_header)
        self.header2.setGeometry(QtCore.QRect(0, 50, 781, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.header2.setFont(font)
        self.header2.setAlignment(QtCore.Qt.AlignCenter)
        self.header2.setObjectName("header2")
        self.logo1 = QtWidgets.QLabel(self.frame_header)
        self.logo1.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.logo1.setText("")
        self.logo1.setPixmap(QtGui.QPixmap("bin/resources/logo.png"))
        self.logo1.setScaledContents(True)
        self.logo1.setObjectName("logo1")
        self.header3 = QtWidgets.QLabel(self.frame_header)
        self.header3.setGeometry(QtCore.QRect(0, 70, 781, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.header3.setFont(font)
        self.header3.setAlignment(QtCore.Qt.AlignCenter)
        self.header3.setObjectName("header3")
        self.logo2 = QtWidgets.QLabel(self.frame_header)
        self.logo2.setGeometry(QtCore.QRect(690, 10, 81, 81))
        self.logo2.setText("")
        self.logo2.setPixmap(QtGui.QPixmap("bin/resources/gcoe.png"))
        self.logo2.setScaledContents(True)
        self.logo2.setObjectName("logo2")
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(10, 130, 511, 381))
        self.display.setFrameShape(QtWidgets.QFrame.Panel)
        self.display.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.display.setText("")
        self.display.setPixmap(QtGui.QPixmap("bin/resources/profile.png"))
        self.display.setScaledContents(True)
        self.display.setObjectName("display")
        self.frame_run = QtWidgets.QFrame(self.centralwidget)
        self.frame_run.setGeometry(QtCore.QRect(540, 130, 251, 171))
        self.frame_run.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_run.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_run.setObjectName("frame_run")
        self.label_run = QtWidgets.QLabel(self.frame_run)
        self.label_run.setGeometry(QtCore.QRect(20, 10, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_run.setFont(font)
        self.label_run.setObjectName("label_run")
        self.runImage = QtWidgets.QPushButton(self.frame_run)
        self.runImage.setGeometry(QtCore.QRect(20, 40, 221, 31))
        self.runImage.setObjectName("runImage")
        self.runVideo = QtWidgets.QPushButton(self.frame_run)
        self.runVideo.setGeometry(QtCore.QRect(20, 80, 221, 31))
        self.runVideo.setObjectName("runVideo")
        self.runWeb = QtWidgets.QPushButton(self.frame_run)
        self.runWeb.setGeometry(QtCore.QRect(20, 120, 221, 31))
        self.runWeb.setObjectName("runWeb")
        self.frame_encode = QtWidgets.QFrame(self.centralwidget)
        self.frame_encode.setGeometry(QtCore.QRect(540, 310, 251, 201))
        self.frame_encode.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_encode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_encode.setObjectName("frame_encode")
        self.label_encode = QtWidgets.QLabel(self.frame_encode)
        self.label_encode.setGeometry(QtCore.QRect(20, 10, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_encode.setFont(font)
        self.label_encode.setObjectName("label_encode")
        self.encodeWeb = QtWidgets.QPushButton(self.frame_encode)
        self.encodeWeb.setGeometry(QtCore.QRect(20, 110, 101, 31))
        self.encodeWeb.setObjectName("encodeWeb")
        self.encodeCap = QtWidgets.QPushButton(self.frame_encode)
        self.encodeCap.setGeometry(QtCore.QRect(130, 110, 101, 31))
        self.encodeCap.setObjectName("encodeCap")
        self.name = QtWidgets.QLineEdit(self.frame_encode)
        self.name.setGeometry(QtCore.QRect(20, 70, 211, 31))
        self.name.setText("")
        self.name.setObjectName("name")
        self.label_name = QtWidgets.QLabel(self.frame_encode)
        self.label_name.setGeometry(QtCore.QRect(20, 50, 67, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.encodeBut = QtWidgets.QPushButton(self.frame_encode)
        self.encodeBut.setGeometry(QtCore.QRect(20, 150, 211, 31))
        self.encodeBut.setObjectName("encodeBut")
        self.frame_status = QtWidgets.QFrame(self.centralwidget)
        self.frame_status.setGeometry(QtCore.QRect(10, 530, 781, 21))
        self.frame_status.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_status.setObjectName("frame_status")
        self.status_body = QtWidgets.QLabel(self.frame_status)
        self.status_body.setGeometry(QtCore.QRect(70, 0, 711, 17))
        self.status_body.setObjectName("status_body")
        self.status_title = QtWidgets.QLabel(self.frame_status)
        self.status_title.setGeometry(QtCore.QRect(10, 0, 67, 17))
        self.status_title.setObjectName("status_title")

        """
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)
        """
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Facial Recognition Software by STARPLAN Research Team"))
        self.header1.setText(_translate("Form", "Facial Recognition Software"))
        self.header2.setText(_translate("Form", "Developed by: De La Salle University, Gokongwei College of Engineering"))
        self.header3.setText(_translate("Form", "STARPLAN Research Team"))
        self.label_run.setText(_translate("Form", "Media"))
        self.runImage.setText(_translate("Form", "Image"))
        self.runVideo.setText(_translate("Form", "Video"))
        self.runWeb.setText(_translate("Form", "Webcam"))
        self.label_encode.setText(_translate("Form", "Encode"))
        self.encodeWeb.setText(_translate("Form", "Webcam"))
        self.encodeCap.setText(_translate("Form", "Capture"))
        self.label_name.setText(_translate("Form", "Name"))
        self.encodeBut.setText(_translate("Form", "Encode"))
        self.status_body.setText(_translate("Form", "Standby"))
        self.status_title.setText(_translate("Form", "STATUS:"))

